### ISSUE TITLE
Create config file for private API key and link to index.html

### ISSUE THREAD

**Issue by zppratt** [zppratt/visualtracert#5]

**Comment by zppratt** [comment]
This could be quite problematic because file access through js is very restricted.  @brewdd02 @SunnyDjinn how to dynamically add a line from a config file to the html?

**Comment by SunnyDjinn** [comment]
We could generate the page entirely via php but that contradicts the asynchronous property we want to implement later.
Now that I think about it, I believe the Google maps key is server related, so we could just send JSON objects from the server to the client , as we did with the REST api?

**Comment by zppratt** [comment]
Seems like a more viable option probably

**Comment by zppratt** [comment]
"Google allows your web site to call any Google API, many thousand times per day.

If you plan for heavier traffic, you should get a free API key from Google.

Go to https://console.developers.google.com to get a free key.

Google Maps expects to find the API key in the key parameter when loading an API:"

Do we need a key?

**Comment by SunnyDjinn** [comment]
Well I guess not! Less work to do!

**Comment by SunnyDjinn** [comment]
@zppratt, where did you find these info and about which API are they?
 I found something similar on W3Schools, but it seems to be about the javascript API, which is client side? 
If we want to retrieve the coordinates on the server side, it seems that we need a key after all (https://developers.google.com/maps/documentation/geolocation/intro):
"Geolocation requests
Geolocation requests are sent using POST to the following URL:

https://www.googleapis.com/geolocation/v1/geolocate?key=YOUR_API_KEY
You must specify a key in your request, included as the value of a key parameter. A key is your application's API key. This key identifies your application for purposes of quota management. Learn how to get a key."

We can do it either from server side or client side. If you know how to retrieve the long/lat from the address using JS, it's fine, otherwise there is a way to do it with server side REST calls.
